### ISSUE TITLE
Add an item to basket

### ISSUE THREAD

**Issue by franzmoro** [franzmoro/artisanalpipes#6]
## Requirements
A user shall be able to:
- Add an item to basket immediately
- Add an item to basket after viewing item info / image gallery.

## Implementation
- [x] Add to basket icon next to item title
- [x] localStorage function
- [x] Checkmark icon as confirmation of add-to-basket
- [x] Remove item from basket
## Tasks
